remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Becas al extranjero desde una perspectiva Guatemalteca
description: Información acerca de becas al Extranjero.
author: Dominic Scott, Julio Bolaños, Mauricio Chin
